flowchart TB
 a[乾杯BABY!]
 b{紙コップで<br>いいんじゃない?}
 c[気持ちが大事]
 d[飾りは]
 dd{あるもので<br>YEAH!IN THE NIGHT?}
 e[アイデア勝負]
 f[愛する人よ]
 g{淋しいときは}
  h[どんな人にも]
  i{あるというのは<br>本当なの?}
  j["<br>超超超！いい感じ！超超超超！いい感じ！\n超超超！いい感じ！超超超超！いい感じ！\n超超超！いい感じ！超超超超！いい感じ！\n超超超！いい感じ！超超超超！いい感じ！<br><br>"]

  a-->b
  b-->|OH YES!|d
  b-->|No|c
  c-->|改心|b
  e-->|再考|dd
  d-->|BABY!|dd
  dd-->|OH YES!|f
  dd-->|No|e
  f-->|TELL ME TELL ME|g
  g-->|BABY BABY|h
  h-->|TELL ME TELL ME |i
  g-->|BABY BABYじゃない|BABYBABYすべき-->|改心|g
  i-->|Yes!|j
  i-->|No|果たして本当か?-->|再考|i
  j-->|"無限ループ"|j


  style j fill:#ffaaaa,stroke:#ff0000,stroke-width:3px
  style BABYBABYすべき fill:#ffffff,stroke:#000000,stroke-width:1px
  style 果たして本当か? fill:#ffffff,stroke:#000000,stroke-width:1px
